name: Doc Generator

on: pull_request
  # push:
  #   branches:
  #     - master
jobs:
  generateDocs:
    name: Generate project documentation
    runs-on: ubuntu-latest

    strategy:
      matrix:  # build matrix for the job
        elixir: [1.10.2]
        otp: [22.2.8]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1 # See documentation for examples of input parameters
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Build docs
        uses: lee-dohm/generate-elixir-docs@v1
      - name: Publish to Pages
        uses: peaceiris/actions-gh-pages@v1.0.1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_DIR: ./doc
          PUBLISH_BRANCH: gh-pages